# Generated by Django 3.2.5 on 2021-11-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_frequent_users_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='room_availability',
            field=models.IntegerField(default=5),
        ),
    ]
