# Generated by Django 3.2.5 on 2021-11-23 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_guest_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 19, 33, 28, 556261)),
        ),
    ]
