# Generated by Django 3.2.5 on 2021-11-23 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_guest_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 20, 33, 13, 175068)),
        ),
        migrations.AlterField(
            model_name='room_booked',
            name='unique_token_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
