# Generated by Django 3.2.5 on 2021-11-23 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211123_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering_orders',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guest'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 22, 52, 29, 326416)),
        ),
    ]
