# Generated by Django 3.2.5 on 2021-11-23 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211123_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequent_users',
            name='UIN',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 1, 3, 46, 770551)),
        ),
    ]
