# Generated by Django 3.2.5 on 2021-11-23 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211124_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequent_users',
            name='UIN',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 1, 9, 15, 451306)),
        ),
    ]
