# Generated by Django 3.2.5 on 2021-11-24 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211124_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='error_message',
            field=models.CharField(default='Error', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 10, 30, 33, 648487)),
        ),
    ]
