# Generated by Django 3.2.5 on 2021-11-24 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211124_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='unique_token_number',
            field=models.CharField(default='asdasd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 22, 54, 32, 687832)),
        ),
    ]
