# Generated by Django 3.2.5 on 2021-11-24 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211124_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='advanced_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 33, 40, 455057)),
        ),
    ]
