# Generated by Django 3.2.5 on 2021-11-24 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211124_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 35, 4, 109739)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='unique_token_number',
            field=models.CharField(max_length=100),
        ),
    ]
