# Generated by Django 3.2.5 on 2021-11-24 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211124_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 36, 2, 472605)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='unique_token_number',
            field=models.CharField(auto_created=True, max_length=100),
        ),
    ]
