# Generated by Django 3.2.5 on 2021-11-24 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211124_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='unique_token_number',
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 37, 4, 213470)),
        ),
    ]
